server:
  port: 80

logger:
  level: info
  syslog: false

users:
  hostname: localhost
  port: 8180

auth:
  hostname: localhost
  port: 8183

rabbitmq:
  url: amqp://localhost/

things:
  protocol: http
  hostname: localhost
  port: 8182

redis:
  url: redis://localhost:6379/0
  expirationTime: 24h
