server:
  port: 80

logger:
  level: info

users:
  hostname: localhost
  port: 8180

authn:
  hostname: localhost
  port: 8183

rabbitmq:
  url: amqp://localhost/

things:
  hostname: localhost
  port: 8182
