server:
  port: 8080

logger:
  level: debug

users:
  hostname: users
  port: 8180

authn:
  hostname: authn
  port: 8183

rabbitmq:
  url: amqp://knot:knot@rabbitmq/

things:
  hostname: things
  port: 8182
