name: Commitlint

on:
  pull_request:
    branches: [ master ]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 20
      - uses: wagoid/commitlint-github-action@v1.6.0
        with:
          configFile: ./commitlint.config.js